"""
===============================================================================
 Project    : Assessing Python’s Suitability for Airborne Safety-Critical
                       Systems under DO-178C Guidelines
 File       : peephole_optimization.py
 Author(s)  : Mohammad Mari, Lian Wen
 Affiliation: School of ICT, Griffith University
 Contact    : mohammad.mari@griffithuni.edu.au
 Created    : 2025
 License    : MIT License (see LICENSE file for details)
 Description: Core experiment code demonstrating peephole optimization in python
 Usage      : python peephole_optimization.py
===============================================================================
"""

# This file illustrates how Python's interpreter applies peephole optimizations
# to bytecode. Peephole optimization is a small-scale, local optimization
# performed on the generated bytecode before execution. It can improve
# performance by simplifying or combining operations
# Output:
#       3           RESUME                   0

#       4           LOAD_CONST               1 (12)
#                   STORE_FAST               0 (x)

#       5           LOAD_FAST                0 (x)
#                 RETURN_VALUE

import dis

def calc():
    x = 6 * 2 # x will be assigned 12; constant propagation is applied here
    return x

print(dis.dis(calc)) # Disassemble and print the bytecode of the `calc` function